### ISSUE TITLE
127.0.0.1 localhost project.dev

### ISSUE THREAD

**Issue by MikeiLL** [chriszarate/docker-compose-wordpress#1]
For me it seemed that when I added:
```
127.0.0.1 localhost project.dev
```
to the OSX `/etc/hosts` file I got an nginx error. Didn't check the nginx logs, but updating the hosts entry to:

```
127.0.0.1  project.dev
```
It served properly.

**Comment by chriszarate** [comment]
If you were getting an Nginx error, then `project.dev` was resolving. Most likely the container wasn't ready to respond, perhaps because you had just started `docker-compose` (it takes about 15-30 seconds to be ready). I would restore `localhost` as you will probably want to resolve `localhost` at some point.

**Comment by MikeiLL** [comment]
Yes. Confirmed that does work as docs suggest.
